# Generated by Django 4.1.7 on 2023-02-27 17:56

import api.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_image_user_image_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=api.models.get_user_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(["jpeg", "png"])
                ],
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="api.profile",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tiers",
                to="api.tier",
            ),
        ),
        migrations.AlterField(
            model_name="thumbnailsize",
            name="size",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(720)]
            ),
        ),
    ]
