# Generated by Django 4.1.7 on 2023-02-28 09:55

import api.models
import django.core.validators
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_image_image_alter_image_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True,
                upload_to=api.models.get_user_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(["jpeg", "png"])
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tier",
            name="thumbnail_size",
            field=models.ManyToManyField(to="api.thumbnailsize"),
        ),
    ]
