# Generated by Django 4.1.7 on 2023-02-28 16:39

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=api.models.get_user_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(["jpeg", "png"])
                ],
            ),
        ),
    ]
